### ISSUE TITLE
[Bug]: Playlist not refreshed after adding some music

### ISSUE THREAD

**Issue by GoKuroko** [ciderapp/CiderUWP-BugTracker#1]
### Describe the Bug
After I added some music to my playlist on Cider 2.x, the playlist was not updated to the latest status. According to my guess, it may be that the application caches the data of the current playlist after opening the playlist for the first time, and the related data is not refreshed after clicking the playlist again.
I have joined the official Discord channel (AnyaForger#5339), please contact me if you have any questions.

### Steps to Reproduce
1. Open the playlist on Cider 2.x.
2. Add some music to the playlist via Cider or Apple music.
3. Then you will find that the playlist was not updated!

### Environment Information
OS: Windows 11 (22621.963)
Desktop Environment:
App Version: Version 2.0.0-.Net
Commit ID:

**Comment by Swiftzerr** [comment]
Currently we have a refresh button on the details of the playlist. We are looking into ways to auto refresh in the background. Thank you for opening this issue.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
