### ISSUE TITLE
Bug/Enhancements: Cider 2 Queue UI

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/CiderUWP-BugTracker#10]
When using the queue feature/infinite song recommendations via the infinite button, the button doesn't hold the "active" red state when closing/reopening the queue. Also doesn't continually add songs to the queue, only adds them in chunks when the previous list was done, which is less visually appealing imo. 

Current build: Cider (EA) 2.0.0 from MS Store

![Screenshot 2023-01-23 114820](https://user-images.githubusercontent.com/123398780/214100312-69f57251-ae62-4121-946a-0adb17c5d64c.png)

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
