### ISSUE TITLE
Can't sort library by title

### ISSUE THREAD

**Issue by beawitcht** [ciderapp/CiderUWP-BugTracker#11]
The sort options in songs has the option Title, but the column of songs is called Name, currently unable to list songs alphabetically

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
