### ISSUE TITLE
Bug: Queue song double playback/error

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/CiderUWP-BugTracker#12]
When selected playlist ends and queue is supposed to start but doesn't begin auto playing, if you select a song in the queue and then press the play button at the bottom, it results in a Playback Error and then begins to play the song doubled up. You can only pause one of the playing songs, the other is stuck being played until it ends.

**Comment by cryptofyre** [comment]
This should be fixed as of the latest update, please inform us if you continue having this issue.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
