### ISSUE TITLE
Bug: On Playback in default view the song and artist may not always update

### ISSUE THREAD

**Issue by artunbekannter** [ciderapp/CiderUWP-BugTracker#13]
The album art will update to the newly playing song at the bottom left, however the song title, artist and album will not update and continue to display the previously playing title. This persists through further song changes (although the album art thumbnail will continue to update).

**Comment by cryptofyre** [comment]
Is this issue related to the iCloud Music Library?

**Comment by artunbekannter** [comment]
> Is this issue related to the iCloud Music Library?

It does seem to be. May have happened from switching from an Apple Music track through to a personal copy of a Soundgarden album that was originally uploaded to Apple Music via iCloud Music Library.

**Comment by cryptofyre** [comment]
Thanks, I've added the iCloud Media Library flair to help assist our investigation.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
