### ISSUE TITLE
Bug: Apple fetch failure prevents further song change.

### ISSUE THREAD

**Issue by artunbekannter** [ciderapp/CiderUWP-BugTracker#14]
On Apple's end sometimes a song will fail to fetch (i.e. if the playback does not start and you click a lyric a "Failed to Fetch" error prompt will appear). If this occurs in Cider the song cannot be changed until Cider is closed and reopened or refreshed. This was produced in the GB region of Apple Music and the failure to fetch seems to be an issue with Apple's post region setting configuration for some songs (possibly cookie related).

Only way to circumvent is currently refreshing Cider. Additionally to get the failed song to playback correctly it requires a sign out of Apple music and clearing the cache file in /WindowsApps/ (A menu option for cache could possibly help resolve this).

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
