### ISSUE TITLE
Bug: Cider Connect Sign in

### ISSUE THREAD

**Issue by artunbekannter** [ciderapp/CiderUWP-BugTracker#16]
This worked on first install, but after subsequently clearing the cache and also reinstalling Cider preview the Sign in now leads to a blank screen. This has been checked on two monitors in case of scaling issues but result is the same on both. Have not managed to resolve this thus far.

GIF attached.

![cider](https://user-images.githubusercontent.com/34310473/214646344-700077fe-b21f-434e-914e-d5bda65a1df0.gif)

**Comment by quacksire** [comment]
We've been working on this component. Should be fixed hopefully next build.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
