### ISSUE TITLE
[Bug]: No lyrics found for songs with non-synced lyrics

### ISSUE THREAD

**Issue by h0ckerman** [ciderapp/CiderUWP-BugTracker#17]
## Describe the Bug
There are some songs that don't have a synced-lyrics, (regular sync, not AM Sing feature), just plain text. The problem is that this text is not displayed in Cider 2.

### <details><summary>Apple Music iOS 14</summary><img alt="Apple Music iOS 14.8.1" src="https://user-images.githubusercontent.com/35598335/215109337-934f097c-fcd4-4bce-9a67-663e7d5ec89c.png" width="40%">
</details>

### <details><summary>Cider 2</summary><img alt="Cider 2 1.0.3.0" src="https://user-images.githubusercontent.com/35598335/215109379-b31f6bbb-3caf-4491-81fd-72c12db1910d.png" width="auto">
</details>

## Steps to Reproduce
Play any song with non-synced lyrics
## Environment Information
OS: Windows 10 21H2 (19044.1706)
App Version: Version 2.0.0-.Net (1.0.3.0)

**Comment by UnbreakCode** [comment]
Apple Music App has grabbed the lyrics from Genius and MusicKit does not provide lyrics from Genius so that won't be possible and isn't a bug

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
