### ISSUE TITLE
animated artworks are darker than normal artworks

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/CiderUWP-BugTracker#18]
animated artworks like mixes are way darker than normal artworks
![image](https://user-images.githubusercontent.com/34512773/215270861-a2645934-92c3-49b8-80fc-1a677459a9b0.png)

![image](https://user-images.githubusercontent.com/34512773/215270848-79d40f70-b292-4890-a00b-d170e5e2342d.png)

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
