### ISSUE TITLE
[Bug]: UI showing incorrect artist/album info for iCloud Music Library Files

### ISSUE THREAD

**Issue by therealvelo** [ciderapp/CiderUWP-BugTracker#19]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 21H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/79325988/215295289-5c20562d-8a4c-4d28-98c4-69101e88ed12.png)
The song "Hardy Boys" has the correct artist info in my playlist, but in the bottom left corner shows a completely different artist/album while playing. The artwork and song name are correct.

### Steps to Reproduce

Any song in my playlist that is in my iCloud Music Library, and not publicly available on Apple Music (uploaded via iTunes) has this issue when playing on Cider.2x

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
