### ISSUE TITLE
[Bug]: Lyrics not cached after playing

### ISSUE THREAD

**Issue by GoKuroko** [ciderapp/CiderUWP-BugTracker#2]
### Describe the Bug
After I play some music on Cider 2.x, every time I open the lyric windows, It will display the text (No lyrics found) first. then it will show the actual lyrics, whether it's the first click or not. According to my guess, It may be that the application didn't cache the lyric data while playing music for the first time.
I have joined the official Discord channel (AnyaForger#5339), please contact me if you have any questions.

### Steps to Reproduce
1. Play some music on Cider 2.x.
2. Click the lyrics button, then you will find the notice 'No lyrics found'.
3. Close the lyrics windows.
4. Click the lyrics button again. This time, the notice 'No lyrics found may flash, but it will still appear.

### Environment Information
OS: Windows 11 (22621.963)
Desktop Environment:
App Version: Version 2.0.0-.Net
Commit ID:

**Comment by GoKuroko** [comment]
> Pretty sure this isn't a bug as i dont think we are caching lyrics at all currently. Seems more like a feature request. Might be something we consider in the future but not a big concern at the moment since lyrics load quickly

Ok, I also think it’s not a bug. This is closer to being a Feature Request. However, when you loaded the lyrics firstly, while playing this song, click the lyrics button again, and the lyrics should not need to be loaded again (it will also show the text ‘No lyrics found’ now). And when you switch the mode to full screen mode, the lyrics will take longer to load. It's really annoying to see that text every time.😂

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
