### ISSUE TITLE
[Bug]: Windows Volume settings get resetted to 100% when restarting Cider 

### ISSUE THREAD

**Issue by MarcSteak** [ciderapp/CiderUWP-BugTracker#20]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

10 and 11

### Describe the Bug

see title

### Steps to Reproduce

1. open Cider 2 EA UWP
2. start playing music
3. lower cider volume via windows volume mixer
4. restart app
5. play music
6. windows settings are back to 100

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
