### ISSUE TITLE
[Bug]: Top-right close buttons get a different color when out of focus

### ISSUE THREAD

**Issue by C0t300** [ciderapp/CiderUWP-BugTracker#21]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Education Version 22H2 22621.1105

### Describe the Bug

when out of focus:
![image](https://user-images.githubusercontent.com/10766743/215831140-a8cae667-1ba1-4b25-b438-6aa1c94a21a1.png)

when focused:
![image](https://user-images.githubusercontent.com/10766743/215831183-04d80538-49ff-4975-b3c5-aec09daabb94.png)

### Steps to Reproduce

- Click outside of cider
- Look at cider

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
