### ISSUE TITLE
[Bug]: Mica effect broken vertically on initial onboarding state

### ISSUE THREAD

**Issue by rlaphoenix** [ciderapp/CiderUWP-BugTracker#22]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 22621.525 (Clean install!)

### Describe the Bug

https://user-images.githubusercontent.com/17136956/215849888-0c7fedbf-7edf-407f-8f31-9ae54173c96a.mp4

As you can see, the mica effect seems to be limited vertically by mistake.
it seems to be fine Horizontally.

### Steps to Reproduce

1. Download from Microsoft Store.
2. Run it.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
