### ISSUE TITLE
[Bug]: State of Sidebar on initial launch is logically incorrect

### ISSUE THREAD

**Issue by rlaphoenix** [ciderapp/CiderUWP-BugTracker#23]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 22621.525 (Clean install!)

### Describe the Bug

![image](https://user-images.githubusercontent.com/17136956/215850494-c638d2ff-5857-4ae5-aa95-3916ca5dd604.png)

This is the exact window dimensions and exact state as of first launch. Not even a mouse hover.
At this size the left sidebar should be visible. However, it did not become visible until I resized the window by 1px.
Afterwards it becomes perfectly fine.

### Steps to Reproduce

1. Install from Microsoft Store.
2. Run it.
3. Accept the initial prompt.
4. Login.
5. Let it restart Cider.
6. Behold the tale of the missing sidebar.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
