### ISSUE TITLE
[Bug]: Not able to play after PC wakes from sleep

### ISSUE THREAD

**Issue by BenBart03** [ciderapp/CiderUWP-BugTracker#24]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 22621.1194

### Describe the Bug

With both Cider and Cider 2 I noticed they will not play music after my PC returns from sleep. On Cider 2 I get the error "Failed to fetch." Simply restarting the program fixes this 

### Steps to Reproduce

Have Cider up and put pc to sleep, then wake back up.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
