### ISSUE TITLE
[Bug]: Unreleased Songs Not Greyed Out

### ISSUE THREAD

**Issue by schellbell** [ciderapp/CiderUWP-BugTracker#25]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19044.2364

### Describe the Bug

When opening up an upcoming album that has some available songs in addition to songs that have not yet been released, there is not visual identification that the unreleased songs are not yet available. For example, in Apple Music all unavailable songs are greyed out, but in Cider they all appear the same. The only clue that you cannot listen to them yet happens when you hover over the small place button beside the track.

### Steps to Reproduce

1. Find an album that has been partially released ([this ](https://music.apple.com/ca/album/with-a-hammer/1654198968)was the one that I saw) 
2. Hitting "Play" for the album will start playing available songs
3. Visually all the tracks appear the same

### Anything else?

![Screenshot 2023-02-01 163058](https://user-images.githubusercontent.com/26511627/216201260-6bcdda7f-7e32-47b1-88b2-7228edbc1302.png)
Only one of the songs above can actually be played.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
