### ISSUE TITLE
[Bug]: Shuffling a playlist does not shuffle all songs in it without a workaround

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/CiderUWP-BugTracker#26]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### Describe the Bug

Clicking the shuffle button at the top of the playlist UI doesn't seem to properly shuffle everything within the playlist. It shuffles the first 100 songs or so, regardless of what the library queue limit is set to in the settings panel. This can be mitigated by scrolling down in the playlist, choosing a song, then activating shuffle from there, but ideally the shuffle playback button should just work.

### Steps to Reproduce

1. Opened a playlist
2. Clicked the shuffle button
3. Only the first 100 songs or so were shuffled

### Anything else?

I did notice this was an issue in Cider Classic as well, so I'm not entirely sure what could be causing the issue.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
