### ISSUE TITLE
[Bug]: Imported songs not showing artwork, and clicking "Go to Abum" on an imported song doesn't work

### ISSUE THREAD

**Issue by bokenbrones** [ciderapp/CiderUWP-BugTracker#27]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Describe the Bug

Local files and folders of music can only be imported currently through iTunes which I understand is not a feature for this version of Cider yet. The imported files from iTunes do show up on Cider though, but their artwork doesn't, and right-clicking then selecting "Go to Album" on imported songs doesn't take you to the imported album they belong to - even though the imported album does show up in Albums.

iTunes: ![image](https://user-images.githubusercontent.com/25750795/216770082-f6167249-376e-4e08-82ca-91ed08551421.png)
Cider:
![image](https://user-images.githubusercontent.com/25750795/216770090-43219ba0-6495-4b3e-bfe7-c1dd0518b582.png)
iTunes:
![image](https://user-images.githubusercontent.com/25750795/216770444-9a4a8d5f-5ce7-43f3-99f0-984a4307d2ed.png)
Cider:
![image](https://user-images.githubusercontent.com/25750795/216770099-55e7c0a6-74e4-4591-9308-a19ea3ce198c.png)

### Steps to Reproduce

Import a local music file or folder through iTunes (as Cider Preview does not seem to currently support this). It will show up in iTunes under Downloaded in the library section, and in Cider Preview under Albums (as well as it adding the songs to Songs). But there is no artwork, and if you right-click and select "Go to Album" there will be no reponse from the UI whereas it works for non-imported songs.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
