### ISSUE TITLE
[Bug]: Immersive mode scroll 

### ISSUE THREAD

**Issue by MatthewT007** [ciderapp/CiderUWP-BugTracker#28]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19045.2546

### Describe the Bug

While in immersive mode, if you reduce the width of the window until only the artwork show, a scroll indicator will show above the 3 buttons (now playing, queue and lyrics). This only goes away once you make the window wider so that the queue / lyrics are shown. 

https://user-images.githubusercontent.com/124470393/216791895-223f0143-abb7-4064-b91f-42d27eddbfb2.mp4

### Steps to Reproduce

Play a song
Click on artwork -> Immersive
Resize window so that only the artwork is showing

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
