### ISSUE TITLE
[Bug]: (Minor) Starting immersive mode causes user lose the ability to find or play songs. 

### ISSUE THREAD

**Issue by foxamine** [ciderapp/CiderUWP-BugTracker#29]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Pro 10.0.19045 Build 19045

### Describe the Bug

Adding a simple search button would solve it, but it's a minor issue (just exit immersive and start your listening). In limited use cases such as my own, however, it does become quite an inconvenience as I am testing casting my display to a 7" touch screen in my car which works best with immersive mode and full screen. This prevents any future features such as default immersive mode(which would be a great add!) if that's something you're interested in pursuing. 

### Steps to Reproduce

Open fresh instance, then go to immersive mode right away. That's all the steps needed and you will succesfully load immersive mode but of course nothing works except "exit" hence why I consider it a  minor issue. Can just load your music beforehand, or back out of immersive then repeat.

### Anything else?

Not sure if relevant but running Windows 10 Pro on an upgraded MacBook Pro 11,4 and sending audio through a USB C (A to C cable) to a Focusrite Scarlett 2i2 Gen 3 entry-level studio interface which outputs to an audiocontrol D6.1200 matrix amplifier/DAC.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
