### ISSUE TITLE
[Bug]: Lyrics may be frozen without auto-scrolling

### ISSUE THREAD

**Issue by GoKuroko** [ciderapp/CiderUWP-BugTracker#3]
### Describe the Bug
After I play some music on Cider 2.x, If you don't click on the application window or focus on the window or others, the lyrics may be stiff without auto-scrolling before your mouse scrolls in the lyrics windows. I don't know the possible cause of the problem.
I have joined the official Discord channel (AnyaForger#5339), please contact me if you have any questions.

### Steps to Reproduce
1. Play some music on Cider 2.x.
2. Click the lyrics button, then the lyrics will freeze until you scroll in the lyrics window with the mouse.

### Environment Information
OS: Windows 11 (22621.963)
Desktop Environment:
App Version: Version 2.0.0-.Net
Commit ID:

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
