### ISSUE TITLE
[Bug]: Sidebar cannot be resized

### ISSUE THREAD

**Issue by mtschirret** [ciderapp/CiderUWP-BugTracker#30]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise, 22621.1105

### Describe the Bug

Cannot resize sidebar by clicking and dragging

### Steps to Reproduce

1. Clicked on vertical sidebar edge; could not drag and resize

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
