### ISSUE TITLE
[Bug]: In immersive mode, the next word/two words end up partially highlighted in lyrics often

### ISSUE THREAD

**Issue by Snaddyvitch-Dispenser** [ciderapp/CiderUWP-BugTracker#31]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Win 10 Pro 19041.630

### Describe the Bug

I expected the lyrics that are on the same line to highlight in order but there were gaps between the highlighted parts sometimes.

### Steps to Reproduce

1. Play a song
2. Go into immersive mode
3. Switch to lyrics
4. When there are 3 short words next to each other, sometimes 2/3 words will be partially highlighted.

### Anything else?

![image](https://user-images.githubusercontent.com/28988626/217340088-d150c333-45d5-439a-8d92-d1175ac6dd00.png)

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
