### ISSUE TITLE
Shuffle and Play not working properly on custom playlist.

### ISSUE THREAD

**Issue by clickers331** [ciderapp/CiderUWP-BugTracker#33]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro | 22H2

### Describe the Bug

So when I press "Shuffle" or "Play" on my own playlist, it seems to not work properly. It is giving me the same three songs when I press shuffle, and another (but the same every time) I press on "Play". It works properly on albums.

### Steps to Reproduce

1. I added a custom song to the playlist (that is not on apple music) to my playlist using iTunes. That might have been the reason but I am not sure.
2. I opened up cider and got onto my playlist
3. I clicked shuffle or play

### Anything else?

Shuffle ===
![Screenshot 2023-02-09 110251](https://user-images.githubusercontent.com/61944296/217752777-28b2e35d-dfc2-44ef-ba5b-c12941a88128.png)

Play ===
![Screenshot 2023-02-09 110601](https://user-images.githubusercontent.com/61944296/217753163-f24aa514-736b-4dcd-bc66-60dc465afba4.png)

Album ===
![image](https://user-images.githubusercontent.com/61944296/217753541-c15d6e02-f29d-4356-8778-aff705a0ae9b.png)

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
