### ISSUE TITLE
[Bug]: Listen Together syncing issues

### ISSUE THREAD

**Issue by Esetrel** [ciderapp/CiderUWP-BugTracker#34]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10/11 version 22H2

### Describe the Bug

As a song is playing there is clicking from the app trying to sync up to Host. The bug goes away when the host pauses.

### Steps to Reproduce

I joined a friend in a listen together and noticed clicking from the music and the time jumping around. When the host paused the music the clicking would stop along with the time jumping around. My friend was on a Windows 10, I am on a Windows 11.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
