### ISSUE TITLE
[Bug]: Live radio streams are broken

### ISSUE THREAD

**Issue by JxMills** [ciderapp/CiderUWP-BugTracker#35]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H1

### Describe the Bug

The new Cider EA doesn't appear to handle Apple Music's Live radio stations / streams, such as BBC Radio 1, Hit Nation, etc, which all currently fail to play. The interface loads the title / text, but fails to display the proper artwork in the now-playing area (shows the thumbnail from a previously played song, paired with the currently selected Live stream title), and fails to play the content (play/stop buttons remain greyed out).

### Steps to Reproduce

Select any recently played live stream or any live stream from search, such as BBC Radio 1, BBC Radio 1Xtra, Hit Nation, Hit Nation Junior, etc.

### Anything else?

As a side, Apple Music radio stations from multiple stream providers should be tested in Cider 2.0 for robustness, as there appears to be minor variation based on provider.

Example: The BBC Radio series of stations ( TuneIn provider ) trigger a MusicKit error under the electron version that causes the playing/stopping of any new station or song to become unresponsive ( plays just fine, just can't stop or play anything else until Cider restarts). Hit Nation streams ( iHeartRadio provider ) play without this bug. 

So some difference between Apple Music's live stream providers exists that can hopefully be mitigated as 2.0 evolves.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
