### ISSUE TITLE
[Bug]: Creating Playlist doesn't work

### ISSUE THREAD

**Issue by JVGA8837** [ciderapp/CiderUWP-BugTracker#36]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2 x64

### Describe the Bug

Went to go create a playlist and would show up on the sidebar, but adding music to it wouldn't work and when I refreshed Cider, the playlist wasn't there. Shows up as an empty playlist on iPhone though.

### Steps to Reproduce

1. Clicked on Create New Playlist
2. Named it
3. Attempted to add music
4. Music didn't show up and refreshed
5. Playlist was gone

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
