### ISSUE TITLE
[Bug]: 播放列表歌曲不能切换排序

### ISSUE THREAD

**Issue by TonyKingWJX** [ciderapp/CiderUWP-BugTracker#37]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

win11 22H2

### Describe the Bug

播放列表里的歌曲不能切换顺序，例如：我换成按添加歌曲的顺序排序，换了没反应！

### Steps to Reproduce

1、点击播放列表
2、点击sort
3、先点击Date Added ,再点击Descending,无反应，再点击Acending,无反应。

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
