### ISSUE TITLE
[Bug]: There's a pause toward the end of songs occasionally. Usually around 10-20 seconds left before the track concludes

### ISSUE THREAD

**Issue by TshiAfro** [ciderapp/CiderUWP-BugTracker#38]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home Single Language

### Describe the Bug

As the track plays, sometimes the audio will cut and the song will stop as if it's lagging or loading, but when this occurs it tends to happen for a few songs consecutively afterwards, & around 10-20 seconds remaining in the song. I expect the track to play all the way through without the pause towards the end.

### Steps to Reproduce

I did not click on anything as the song would pause and continue by itself.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
