### ISSUE TITLE
[Bug]: Some buttons seem to be missing on the bottom bar

### ISSUE THREAD

**Issue by Chicchi7393** [ciderapp/CiderUWP-BugTracker#40]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### Describe the Bug

I think there should be some buttons here, but somehow they aren't showing. If it was meant to have no buttons there (i mean like lyrics button) the volume slider should be on the right

### Steps to Reproduce

1. just started a song

### Anything else?

![image](https://user-images.githubusercontent.com/25307474/219466696-e6c31b3a-abac-4f5d-ae65-3f828bf95c9d.png)

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
