### ISSUE TITLE
[Bug]: Cannot create new playlist from an almbum

### ISSUE THREAD

**Issue by babelmansour2** [ciderapp/CiderUWP-BugTracker#41]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22623

### Describe the Bug

When adding an album to the library, I do no longer have the possibility to create a new playlist, only to add the album to an already existing playlist.

### Steps to Reproduce

1. click on the three dots of an album image
2. add to a playlist
3. create a new playlist option not available

**Comment by sanhuesoft** [comment]
+1 on this!

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
