### ISSUE TITLE
[Bug]: Nothing shows up when searching music while in multitasking 

### ISSUE THREAD

**Issue by shaqoncracc** [ciderapp/CiderUWP-BugTracker#42]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19045.2604

### Describe the Bug

When searching for music while multitasking with another app no music shows up. 
![Cider issue 1](https://user-images.githubusercontent.com/125750979/219977817-42621af6-7308-4f7c-be08-89207e6c9416.png)

### Steps to Reproduce

Search for music in Cider while multitasking with another app.

**Comment by RedBeardedVikingDK** [comment]
+1 to this error.

After searching a title / song one must clicked on another tab (Home / Listen Now) before another search can be performed.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
