### ISSUE TITLE
[Bug]: Theme Editor opens apple music webplayer instead of theme editor

### ISSUE THREAD

**Issue by DecibillyJoel** [ciderapp/CiderUWP-BugTracker#45]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Describe the Bug

Trying to open the theme editor in the latest alpha fujisan build instead opens https://beta.music.apple.com/theme-ed/index.html

### Steps to Reproduce

1. Click the three dots on the top left
2. Click Settings
3. Click Advanced
4. Click "Open Theme Editor"
5. Have fun

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
