### ISSUE TITLE
[Bug]: Media_License Error and inabilty to activate apple music as an account option. 

### ISSUE THREAD

**Issue by stevensoncrash** [ciderapp/CiderUWP-BugTracker#46]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### Describe the Bug

I am unable to play any song currently and am unable to activate apple music as an account in settings.  I have reset the app several times and continue to receive the Media_License errors dispite me signing into my apple account. Addiotnally ApplePod casts are no longer shown as a media library option. 

Any help and getting this app up and running would be much appreciated. Alpha still works fine and is kicking ass. 

### Steps to Reproduce

I signed into my account upon app startup.

Clicked on any song and immediately recieved an error. 

![Screenshot 2023-02-24 MEDIA_LICENSE Error](https://user-images.githubusercontent.com/30736470/221328812-6f12f8d3-6024-499d-b443-d10ebf08bc79.png)

Dove through the settings and found that the apple music option could not be checked. Signed in muliple times and contined to recieve the above error. 

![Screenshot 2023-02-24 apple music cannot be enabled](https://user-images.githubusercontent.com/30736470/221328455-479a2820-07c3-4a1b-8647-38d5009f3add.png)

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
