### ISSUE TITLE
[Bug]: Changing the Discord RPC Client Name to Apple Music doesn't actually do anything.

### ISSUE THREAD

**Issue by Sogiq91** [ciderapp/CiderUWP-BugTracker#47]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### Describe the Bug

When you open the settings and go to Connectivity and change the client name to Apple Music, it stays on Cider 2 and won't change.

### Steps to Reproduce

Open Settings > Connectivity > Client Name, Change it to "Apple Music," check Discord RPC.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
