### ISSUE TITLE
[Bug]: Plays wrong song and messes up title, artist and album

### ISSUE THREAD

**Issue by nevotheless** [ciderapp/CiderUWP-BugTracker#48]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 22H2 (OS Build 22621.1265)

### Describe the Bug

When i try to play a song in one of my playlists it sometimes happen that cider get's confused an can't display any information about the song playing correctly anymore. It also doesn't play the song i selected in the first place.

**Example**
![grafik](https://user-images.githubusercontent.com/779797/221374223-65038be5-661e-43ff-a812-008456b80b26.png)

In this case i tried to play "good one matt". It play's the song below it and shows absolutely wrong album info. 

### Steps to Reproduce

1. Clicked on a song in my playlist 
2. It plays a different song
3. It also shows wrong album information about the played song in this case

### Anything else?

Let me know if there's something i can do to debug this further.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
