### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JimDude7404** [ciderapp/CiderUWP-BugTracker#49]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10, 21H2

### Describe the Bug

Well, when it prompts that the app needs to rebooted for a theme change etc, it will just present me with this screen 
![image](https://user-images.githubusercontent.com/67085206/221614197-a5472a83-92df-4de9-9bb8-2337b823fbce.png)
I

### Steps to Reproduce

Just go and change the theme and click Okay, and the app will not reboot itself

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
