### ISSUE TITLE
Cider 2.x Feedback

### ISSUE THREAD

**Issue by ScytheDEM** [ciderapp/CiderUWP-BugTracker#5]
Hi, just brought the 'Microsoft Store EA' release of Cider 2.0 and after using it for 1/2 an hour i've got some things that could be improved.

Pros:
- Holy crap the music sounds clearer, like a lot clearer. 
- It feels amazing on a 144hz monitor, like absolute butter. 
- HOLY, IT'S FAST. 

Cons:
- Lyrics 'sing' feature displays 'long notes' really weirdly, almost if they aren't in time? But sometimes produces other weird results such as notes hanging for too long. 
- not a huge fan of the 'lyrics, search, queue, etc' buttons being at the top of the screen, allowing people to move them down (beside the 'bottom bar music player' would be a nice touch
- Everything feels- connected? All the colours blend into each other and make (if this makes sense) it feel like one blank canvas with different sub menus that aren't separated enough
(for example, my attached screenshot)

https://pasteboard.co/cmCwPQQDGvRR.png
- the SZA 'album' feels like it's 'floating' but everything behind it feels all together? i feel like more separation should be added.

you guys have done an amazing job and please keep it up!

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
