### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wbahia** [ciderapp/CiderUWP-BugTracker#51]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

windows 11

### Describe the Bug

After minimize the app and return to the original state there is a bug in how it´s show. Probably a resolution issue.
<img width="742" alt="image" src="https://user-images.githubusercontent.com/16428732/222728752-5af16002-f3a6-4256-a75b-a46a17d8655e.png">

### Steps to Reproduce

1. minimize app
2. click on task bar to maximize
3. the icons does not fill the
<img width="742" alt="image" src="https://user-images.githubusercontent.com/16428732/222729138-99643c1e-ee79-4a1f-a866-2ce81ad2a52f.png">
 screen (resolution issue??)

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
