### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BlackTyph00n** [ciderapp/CiderUWP-BugTracker#52]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### Describe the Bug

While playing music, skipping, forwarding a song shows "Playback Error" as shown 
![image](https://user-images.githubusercontent.com/110780419/223188214-ffe59dec-374e-4df4-8aae-4bcaa25e50a6.png)
although the error shows up the songs keep playing with no issues.

### Steps to Reproduce

1-Playing any song or Playlist
2-Skipping the song

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
