### ISSUE TITLE
[Bug]: End of Playback artist link

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/CiderUWP-BugTracker#53]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Win 11 22H2 22621.1344

### Describe the Bug

After a playlist or song playback is completed, Artist name no longer links to the song artist when left clicked. It WILL still work when song is playing or paused partway through.
![image](https://user-images.githubusercontent.com/123398780/223216756-0c5c8c6b-05f4-49b4-bc4f-48fe32189e95.png)

### Steps to Reproduce

play a song/playlist, wait for it to complete. Try to left click artist name in bottom left - no worky.

### Anything else?

Tested on FujisanCore build, but might also be a problem on other builds.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
