### ISSUE TITLE
[Bug]: App Settings don't persist on restart

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/CiderUWP-BugTracker#54]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

11 22H2 build 

### Describe the Bug

Any time you restart the app, Discord rich presence, cider audio, and a few other settings will be reset to default.
PRE APP RESTART
![image](https://user-images.githubusercontent.com/123398780/223218269-08ad0234-1c5e-4133-8621-ebef8cc1e482.png)
![image](https://user-images.githubusercontent.com/123398780/223218361-319e5b57-db0b-4040-a945-5fcf57427062.png)
POST APP RESTART
![image](https://user-images.githubusercontent.com/123398780/223218453-bd205766-970f-4c99-99e0-cc807fbc97a0.png)
![image](https://user-images.githubusercontent.com/123398780/223218530-e2d456cd-60df-4a13-a6a7-a7bb5859e3c7.png)

### Steps to Reproduce

Check Discord RP and cider audio settings, then restart app. they will be defaulted post restart.

### Anything else?

Tested on recent Fujisan build

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
