### ISSUE TITLE
[Bug]: Shuffling playlists recycles a handful of songs rather than truly shuffling

### ISSUE THREAD

**Issue by dominator24** [ciderapp/CiderUWP-BugTracker#55]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [ ] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Describe the Bug

Everytime I shuffle a playlist (5000+ songs) the same handful of songs keep appearing in a slightly different order instead of a true shuffle.

### Steps to Reproduce

I clicked shuffle a handful of times and looked at the queue

**Comment by NathanielH-snek** [comment]
I see its marked as pending but yeah same here.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
