### ISSUE TITLE
[Bug]: Pressing play on a song deep within a custom playlist instead plays a random song. 

### ISSUE THREAD

**Issue by Kylepossible** [ciderapp/CiderUWP-BugTracker#56]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Describe the Bug

In a playlist with about 350~ songs. It will not play the song selected after the 200th~ song. 
Instead it will fallback to a random song within the playlist, prior to where that break is.

I confirmed by clicking through songs within my custom playlist and figured out at a certain point(I didn't count exactly how many songs I went down...but estimate around the 200-250th line item) it will not play any songs past that line item but it will consistently play any song before that threshold. 

Tried uninstalling/reinstalling, reset app data, etc 

### Steps to Reproduce

Create a large playlist of songs(350+)
Attempt to play songs near the end of the playlist.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
