### ISSUE TITLE
[Bug]: Can't click buttons when lyrics window is open on Mavericks Player Layout

### ISSUE THREAD

**Issue by JVGA8837** [ciderapp/CiderUWP-BugTracker#57]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2 x64

### Describe the Bug

![image](https://user-images.githubusercontent.com/67811123/224469187-75142148-41e6-46ff-8bb3-3b6928493165.png)

### Steps to Reproduce

1. Select Mavericks Player Layout
2. Select Show Lyrics Button

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
