### ISSUE TITLE
[Bug]: Unable to use scroll wheel to scroll

### ISSUE THREAD

**Issue by Cl3ffy** [ciderapp/CiderUWP-BugTracker#58]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home Version 22H2 (OS build 22621.1413)

### Describe the Bug

I am unable to use my scroll wheel to navigate the interface or to change volume.

If this issue is not affecting everyone, let me know what I should do or what kind of information you need to help investigate this issue.
If this is a known thing and scrolling just hasn't been implemented yet, I apologize. You may close this issue and carry on. 

### Steps to Reproduce

1. Open the Cider™ 2 application.
2. Click on the application interface to make sure it's focused.
3. Move your hand on top of your hand-held pointing device.
4. Move your finger (usually index finger) on top of the scroll wheel of your hand-held pointing device.
5. Now move the finger up and down while gently pressing onto the scroll wheel with your index finger.
6. See if there is any movement within the interface or if the volume is changing when you are hovering over the volume bar.

**Comment by p4p4-3ch0** [comment]
I'm finding (on Windows 11) that the scrollwheel on my Logitech Master mouse is actually zooming the Cider interface in and out, as if I were holding the CTRL key.

**Comment by p4p4-3ch0** [comment]
👆 This seems intermittent.  After clicking through to here from the create bug/issue report menu option the scrolling was working again, but I couldn't play any music.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
