### ISSUE TITLE
Bug: Last.fm Integration not working

### ISSUE THREAD

**Issue by EternalDesire** [ciderapp/CiderUWP-BugTracker#6]
when i tried to link my Last.fm account with Cider (EA) this happens after i click the yes, allow accept button:
![image](https://user-images.githubusercontent.com/100450669/214003910-17b1364b-e540-4629-a821-b6ca537ac9bf.png)
tried with vpn on and off and it still the same.

**Comment by cryptofyre** [comment]
This happens due to the lack of callbacks required to make things function as it should, we'll be investigating it while we continue adding additional backend features.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
