### ISSUE TITLE
[Bug]: Scrolling Issues in Cider (EA)

### ISSUE THREAD

**Issue by Rauf321X** [ciderapp/CiderUWP-BugTracker#61]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 21H2 

### Describe the Bug (fairly explainable)

When scrolling in Cider (EA), it's choppy and sometimes doesn't work. It stops when you're scrolling and sometimes scrolls the other direction.

### Steps to Reproduce (not very hard to reproduce though)

1. Went on any of the Cider UI, mostly the Home page.
2. Start scrolling, and the issue should appear.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
