### ISSUE TITLE
[Bug]: Apple music logged in, but not connected.

### ISSUE THREAD

**Issue by junkypurr** [ciderapp/CiderUWP-BugTracker#62]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### Describe the Bug

On Cider 2.0, after authenticating with Apple Music, other features that require Apple Music (such as Cider Audio Labs) do not recognize that it's connected. 

### Steps to Reproduce

1. Authenticate with Apple music
2. Click on "Cider Audio Labs" (the headphone icon)

also look at Settings > Connections. Apple Music should be greyed out, despite the "Apple Music" button hidden under the 3 dots in the top-left corner prompt you to sign out. 

### Anything else?

![image](https://user-images.githubusercontent.com/50148641/228387672-6b7def51-2fc5-4d92-a60d-c3f8d5e70d57.png)
![image](https://user-images.githubusercontent.com/50148641/228387698-e2c808a1-b505-44a5-a0d7-eb34aa5336e1.png)
![image](https://user-images.githubusercontent.com/50148641/228387721-5179766b-eee1-47d5-ae4f-d1ebc4187e92.png)

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
