### ISSUE TITLE
[Bug]: Intelligent playlists not visible

### ISSUE THREAD

**Issue by DeN-AlB** [ciderapp/CiderUWP-BugTracker#63]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### Describe the Bug

Intelligent playlists not visible. I created some intelligent playlists on Apple Music, but they are not shown in Cider Preview.

### Steps to Reproduce

1. Create an intelligent playlist on Apple Music.
2. Open Cider Preview and the playlist should not be there.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
