### ISSUE TITLE
[Bug]: Glitchy Screen

### ISSUE THREAD

**Issue by PontiffSul** [ciderapp/CiderUWP-BugTracker#65]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Describe the Bug

Glitchy screen when performing functions and hovering over buttons. 

### Steps to Reproduce

Opened the cider app and started to perform functions. 

### Anything else?

https://user-images.githubusercontent.com/129639685/229330716-ef455fbd-d587-4e94-89df-fdb096d57878.mp4

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
