### ISSUE TITLE
[Bug]: Blank Cider app window after relaunching the app

### ISSUE THREAD

**Issue by OnePeach47** [ciderapp/CiderUWP-BugTracker#67]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### Describe the Bug

Blank Cider window after relaunching Cider.

### Steps to Reproduce

1. Reset the Cider app from the settings
2. Launch Cider and log in for the first time
4. Play some music
5. Exit Cider
6. Launch it again

### Anything else?

![Blank Cider app window](https://user-images.githubusercontent.com/54127572/230372904-b32203a1-0f7a-4be0-a2d0-698c8bb6fc13.png)

**Comment by Flynn95** [comment]
Same issue, happens after updating to new version of Cider

**Comment by globae02** [comment]
i uninstalled and reinstalled and it fixed for me

**Comment by OnePeach47** [comment]
> i uninstalled and reinstalled and it fixed for me

They're already patched it in the latest update 4 days ago.
