### ISSUE TITLE
[Bug]: Stuck on 256 Kbps (High Quality) instead of 16-bit/44,1 kHz (Lossless) and 24-bit/192 kHz (Hi-Res Lossles)

### ISSUE THREAD

**Issue by OnePeach47** [ciderapp/CiderUWP-BugTracker#68]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/CiderUWP-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows

### Operating System Version

Windows 11H2

### Describe the Bug

When I'm playing some tracks with lossless and hi-res lossless available, Cider can only play tracks can only be played with 256 Kbps AAC, while Apple Music for Windows can play it up to hi-res lossless (I can't prove it scientifically, but my ears can tell the difference).

### Steps to Reproduce

1. Play some tracks with Hi-Res lossless availability (DRM configured to Default).
2. The track plays at 256 Kbps (High Quality).
3. Change the DRM into PlayReady and restart Cider.
4. The track still plays at 256 Kbps.
5. Change the DRM into Widevine and restart Cider.
6. The track still plays at 256 Kbps.

Are these DRM issues, or is Cider incapable of playing a hi-res lossless song? Usually, PlayReady DRM can decrypt much higher quality. Like Netflix and Apple TV, it can play UHD videos using this DRM. But in Cider, it stuck at high quality, even though the DRM has changed to PlayReady.

### Anything else?

![Screenshot 2023-04-15 041259](https://user-images.githubusercontent.com/54127572/232158276-f461c348-a505-4aed-a51e-e6881e9743b9.png)

**Comment by Flynn95** [comment]
I don't think Apple MusicKit.JS provides playback in higher quality (lossless/atmos), which Cider is using

**Comment by OnePeach47** [comment]
> ~I don't think Apple MusicKit.JS provides playback in higher quality (lossless/atmos), which Cider is using~ Edit: Found the discussion here: https://github.com/orgs/ciderapp/discussions/889

Yes, I'm aware of that discussion, but I thought Cider 2.0 would support Lossless/Hi-Res Lossless
![image](https://user-images.githubusercontent.com/54127572/232202512-b796c240-becc-47fb-ac81-69d7e0913306.png)

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
