### ISSUE TITLE
Bug: Discord Rich Presence not working

### ISSUE THREAD

**Issue by EternalDesire** [ciderapp/CiderUWP-BugTracker#7]
already restarted both Cider 2.x UWP and Discord but Rich Presence is still not working/showing, and yes the setting is already toggled on.

![image](https://user-images.githubusercontent.com/100450669/214008444-3e10a471-81ad-43e6-ad20-251f33534966.png)

**Comment by cryptofyre** [comment]
Currently placeholder functions, we've not yet set up the backend required for these features to work.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
