### ISSUE TITLE
Listen Together windows goes over other buttons

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/CiderUWP-BugTracker#9]
I can't close the window anymore because I can't press the button 
![image](https://user-images.githubusercontent.com/34512773/214094837-00d43e1a-1afb-44ed-84ad-a26eaaf83982.png)

**Comment by Stalloevan** [comment]
Same issue here. Would recommend moving it down, and including a close button in addition to the option of just clicking the icon.

**Comment by coredev-uk** [comment]
Cider-UWP & Cider-Fujisan have been abandoned in favour of Cider-Sabiiro. Please update your clients and if the issue persists you can submit requests [here](https://github.com/ciderapp/Sabiiro-BugTracker/issues).

This issue will be closed.
